spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/giant
    username: postgres
    password: # Set your DB password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type: trace

jwt:
  access:
    secret: # Set your secret key
    expiration: 30m
  refresh:
    secret: # Set your secret key
    expiration: 14d

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.flywaydb: debug