spring:
  application:
    name: giant
  datasource:
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: UTC
  profiles:
    active: local

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html # ğŸ‘‰ OpenAPI JSON ë¬¸ì„œ ê²½ë¡œ (ê¸°ë³¸: /api-docs)
  api-docs:
    path: /api-docs  # ğŸ‘‰ Swagger UI ì ‘ì† ê²½ë¡œ (ê¸°ë³¸: /swagger-ui/index.html)